server:
  port: 8803

spring:
  application:
    name: cloud-stream-consumer       #注册进eureka服务列表的服务名
  cloud:
    stream:
      binders:              #绑定rabbitmq服务信息
        defaultRabbit:      #整合rabbitmq
          type: rabbit      #消息组件类型
          enviroment:       #设置rabbitmq的环境配置
            spring:
              #rabbitmq的支持
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:             #服务整合的处理
        input:              #通道名称
          destination: studyExchange      #定义使用的Exchange
          content-type: application/json  #设置消息类型  文本为text/plain
          binder: defaultRabbit           #绑定的消息服务
          group: Ivan                     #分组名称(同一个组会发生竞争,只有一个消费者消费消息,不同的组都可以消息消息)


#注册到eureka服务列表中
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka  # 单机版
  instance:
    lease-renewal-interval-in-seconds: 2         #心跳时间  默认30秒
    lease-expiration-duration-in-seconds: 5      #超时时间  默认为90秒
    instance-id: receive-8803.com                   #主机名称
    prefer-ip-address: true                      #访问路径为ip

