server:
  port: 80

eureka:
  client:
    register-with-eureka: false   #true表示向注册中心注册自己
    service-url:
#      defaultZone: http://localhost:7001/eureka # 单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群版


#设置feign客户端的超时时间,默认为1秒,超过1秒若没有得到请求响应就会报错
ribbon:
  #等待请求响应最长时间
  ReadTimeout: 5000
  #建立连接最长等待时间
  ConnectTimeout: 5000

#feign的日志功能
logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.ivan.springcloud.service.PaymentFeignService: debug